# For Development only

version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "backend"
    ports:
      - 5432:5432
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8032:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=1234
