// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemLevelRessource } from "./ItemLevelRessource";

export interface GameRessource { id: number | null, ended: boolean, score: number, coins: number, lives: number, enemy_spawn_timeout: number, items: Array<ItemLevelRessource>, }