// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ItemRessource { id: number, name: string, description: string, price: number, }