// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemRessource } from "./ItemRessource";

export interface ItemLevelRessource { level: number, item: ItemRessource, }