apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ CI_COMMIT_REF_NAME }}-backend"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "{{ CI_COMMIT_REF_NAME }}-backend"
  template:
    metadata:
      labels:
        app: "{{ CI_COMMIT_REF_NAME }}-backend"
    spec:
      imagePullSecrets:
      - name: gitlab-registry-{{ CI_PROJECT_ID }}
      containers:
      - name: app
        image: "{{ CI_REGISTRY_IMAGE }}/backend-{{ CI_COMMIT_REF_NAME }}:latest"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /api/v1/healthz
            port: 5000
          periodSeconds: 60
          failureThreshold: 1
        resources:
          requests:
            cpu: "50m"
            memory: "16Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"
        env: 
          - name: "DATABASE_URI"
            value: 'postgresql://backend@postgres:5432/backend'
          - name: "SECRET"
            value: "{{ FLASK_SECRET }}"

