apiVersion: v1
kind: Service
metadata:
  name: "{{ CI_COMMIT_REF_NAME }}-backend-svc"
spec:
  selector:
    app: "{{ CI_COMMIT_REF_NAME }}-backend"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
