apiVersion: v1
kind: Service
metadata:
  name: "{{ CI_COMMIT_REF_NAME }}-frontend-svc"
spec:
  selector:
    app: "{{ CI_COMMIT_REF_NAME }}-frontend"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
